DOMAIN = "blomster_maintenance"
STORAGE_VERSION = 1
STORAGE_KEY = f"{DOMAIN}.data"

CONF_WATER_SOURCE_ENTITY = "water_source_entity"
CONF_WATER_INSTALLATION_DATE = "water_installation_date"
CONF_BLADE_USAGE_ENTITY = "blade_usage_entity"
CONF_BLADE_WARNING_ENTITY = "blade_warning_entity"
CONF_BLADE_INTERVAL_HOURS = "blade_interval_hours"
DEFAULT_BLADE_INTERVAL_HOURS = 150.0

SERVICE_SET_WATER_BASELINE = "set_water_baseline"
SERVICE_CONFIGURE_ITEM = "configure_item"
SERVICE_RECORD_MAINTENANCE = "record_maintenance"
SERVICE_DELETE_MAINTENANCE = "delete_maintenance"
SERVICE_IMPORT_WATER_HISTORY = "import_water_history"
SERVICE_ACKNOWLEDGE_MAINTENANCE = "acknowledge_maintenance"

ATTR_BASELINE_LITERS = "baseline_liters"
ATTR_ITEM_ID = "item_id"
ATTR_EVENT_ID = "event_id"
ATTR_NAME = "name"
ATTR_NOTE = "note"
ATTR_COST = "cost"
ATTR_METER_ENTITY = "meter_entity"
ATTR_CATEGORY = "category"
ATTR_LOCATION = "location"
ATTR_MANUFACTURER = "manufacturer"
ATTR_MODEL = "model"
ATTR_SERIAL_NUMBER = "serial_number"
ATTR_INSTALLED_AT = "installed_at"
ATTR_INTERVAL_TYPE = "interval_type"
ATTR_INTERVAL_VALUE = "interval_value"
ATTR_MANUAL_URL = "manual_url"
ATTR_RECEIPT_URL = "receipt_url"
ATTR_IMAGE_URL = "image_url"
ATTR_WARNING_ENTITIES = "warning_entities"

WATER_SENSOR_UNIQUE_ID = f"{DOMAIN}_water_total"
BLADE_REMAINING_SENSOR_UNIQUE_ID = f"{DOMAIN}_blade_remaining"
BLADE_DUE_BINARY_SENSOR_UNIQUE_ID = f"{DOMAIN}_blade_due"
SERVICEBOOK_SENSOR_UNIQUE_ID = f"{DOMAIN}_servicebook"
EVENT_WATER_UPDATED = f"{DOMAIN}_water_updated"
EVENT_MAINTENANCE_UPDATED = f"{DOMAIN}_maintenance_updated"
EVENT_MAINTENANCE_REMINDER = f"{DOMAIN}_maintenance_reminder"
